Adds get_chain

diff --git a/bin/certlib b/bin/certlib
--- a/bin/certlib
+++ b/bin/certlib
@@ -109,6 +109,10 @@ function generatekey {
 	fi
 }
 
+function cert_extract {
+	awk 'BEGIN{c=0}c==1{b=b"\n"$0}/^-----BEGIN (TRUSTED )?CERTIFICATE-----/{c=1;b=$0}/^-----END (TRUSTED )?CERTIFICATE-----/{print b;c=0;b=""}'
+}
+
 function retrieve_cert {
 
 	[ -n "${1}" ] || die "$0: argument expected"
@@ -126,13 +130,17 @@ function retrieve_cert {
 			f="\"${1}\""
 			input="$(cat "${1}")"
 		fi
-		
-		if ! cert="$(echo "${input}" | openssl x509 -inform PEM)"; then
-			if ! cert="$(echo "${input}" | openssl x509 -inform DER)"; then
-				die "Openssl could not identify the contets of ${f} as either a PEM encoded or DER encoded certificate."
+	
+		if [ -n "${RETRIEVE_CHAIN:-}" ]; then
+			cert="$(echo "${input}" | cert_extract)"
+		else
+			if ! cert="$(echo "${input}" | openssl x509 -inform PEM)"; then
+				if ! cert="$(echo "${input}" | openssl x509 -inform DER)"; then
+					die "Openssl could not identify the contets of ${f} as either a PEM encoded or DER encoded certificate."
+				fi
 			fi
 		fi
-		[ -n "${cert}" ] || die "No certificate found."
+		[ -n "${cert}" ] || die "No certificate or chain found."
 	else
 		host="$(echo "${1}" | cut -d: -f 1)"
 		[ -n "${host}" ] || die "Unable to extract host from \"${1}\"."
@@ -149,8 +157,17 @@ function retrieve_cert {
 		sni="${2:-}"
 		[ -n "${sni}" ] || sni="${host}"
 		ret=0
-		cert="$(echo -n "" | openssl s_client -connect "${host}:${port}" -servername "${sni}" 2>/dev/null| \
-			openssl x509 2>/dev/null)" || die "Unable to connect to \"${1}\" and extract a certificate."
+		[ -n "${RETRIEVE_CHAIN:-}" ] && show="-showcerts" || show="" 
+		cert="$(echo -n "" | openssl s_client -connect "${host}:${port}" -servername "${sni}" ${show} 2>/dev/null)"
+
+		if [ -n "${RETRIEVE_CHAIN:-}" ]; then
+			cert="$(echo "${cert}" | cert_extract)"
+		else
+			cert="$(echo "${cert}" | openssl x509 2>/dev/null)"
+		fi
+
+		[ -n "${cert}" ] || die "Unable to connect to \"${1}\" and extract a certificate."
+
 	fi
 
 	printf "%s\n" "${cert}"
